// Real Organization API connected to backend
export { 
  useCreateOrganizationMutation,
  useGetOrganizationsQuery,
  useGetOrganizationQuery,
  useUpdateOrganizationMutation,
  useDeleteOrganizationMutation,
  useJoinOrganizationMutation,
  useLeaveOrganizationMutation,
  useGetOrganizationMembersQuery,
  useUpdateMemberRoleMutation,
  useRemoveMemberMutation,
  useGenerateInviteCodeMutation,
  useGetInviteCodesQuery,
  useDeactivateInviteCodeMutation,
  useGetCurrentUserOrganizationQuery,
  // New organization settings endpoints
  useGetOrganizationSettingsQuery,
  useUpdateOrganizationSettingsMutation,
  useInviteMemberMutation,
  useResendInvitationMutation,
  useCancelInvitationMutation,
  // Type exports
  type Organization,
  type OrganizationMember,
  type InviteCode,
  type CreateOrganizationRequest,
  type UpdateOrganizationRequest,
  type JoinOrganizationRequest,
  type GetOrganizationsParams,
  type GetMembersParams,
} from './realOrganizationApi';